### ISSUE TITLE
On se revoit ?

### ISSUE THREAD

**Issue by ludovicdeluna** [wi2/sails-auto-admin#1]
Hello,

La dernière fois on s'est croisé rapidement.
On pourrait se revoir ? C'est quoi ton e-mail ?

Ludo.

**Comment by wi2** [comment]
Yes.. j'ai eu benoit .. ça ne sera pas avant décembre pour lui...
Mais que penses tu de la semaine prochaine..
michael.gaeta@af83.com

**Comment by ludovicdeluna** [comment]
Thanks !
